title: Khanh N. Dang
author: Khanh N. Dang
# email: your-email@domain.com
# description:
site-starting-year: 2014

google_analytics: UA-52343779-2

url: "http://web-ext.u-aizu.ac.jp"
baseurl: "/~khanh"

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
  - about.md
  - research.md
  - pub.md
  # - patent.md
  - service.md
  - teaching.md
  # - mentor.md
  - contact.md
  - to-lab.md

paginate: 5

markdown: kramdown

kramdown:
  parse_block_html: true

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec

paginate_path: "/news/page:num/"

