name: Khanh's Site
description: A website by me.
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://www.dangnamkhanh.com'
google_analytics: 'UA-52343779-2'

# Details for the RSS feed generator
url:            'www.dangnamkhanh.com'
author:         'Your Name'
