name: Khanh's personal site
description: stuffs, profiles, anythings
meta_description: "My Site: adksjdqorieancmvaafhf "

aboutPage: true

markdown: redcarpet
highlighter: rouge

paginate: 20
baseurl: 
domain_name: 'http://www.dangnamkhanh.com'
google_analytics: 'UA-52343779-2'
disqus: yes
disqus_shortname: 'dnk0904'

# Details for the RSS feed generator
url:            'http://www.dangnamkhanh.com'
author:         'Khanh N. Dang'
authorTwitter:  'twitter'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
