title: Khanh N. Dang
author: Khanh N. Dang
# email: your-email@domain.com
description: >
  Hi! You are visiting my website. My name is <strong>Khanh N. Dang</strong>. 
  I am an <em>Assistant Professor</em> of <a href="https://e.uet.vnu.edu.vn/">VNU-UET</a>, 
  <a href="https://vnu.edu.vn/eng/">Vietnam National University, Hanoi (VNU)</a>. 
  My research topics are <a href="./research">neuromorphic computing</a>, 
  <a href="./research">3D Integrated Circuits technology</a>, 
  <a href="./research">Artificial Intelligence for CAD</a>, and <a href="./research">fault-tolerant computing</a>.<br><br>
  <a href="./about">» About me</a>

google_analytics: UA-52343779-2

url: "http://khanhdang.github.io/"
baseurl: ""

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
  - about.md
  - research.md
  - pub.md
  - course.md
  - service.md
  # - grant.md
  - contact.md

paginate: 5

markdown: kramdown

kramdown:
  parse_block_html: true

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec

paginate_path: "/news/page:num/"

