
#-------------------------------
# Work Section

projects:
- {name: 'Neuromorphic Computing', folder: 'neuromorphic', file: 'research.html#neuromorphic-computing'}
- {name: 'AI for Computer-Aided Design', folder: 'mlcad', file: 'research.html#ai-for-computer-aided-design'}

